/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedEngineerRouteImport } from './routes/_authenticated/engineer'
import { Route as AuthenticatedCommissionsRouteImport } from './routes/_authenticated/commissions'
import { Route as AuthenticatedChiefRouteImport } from './routes/_authenticated/chief'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFulfillmentIdRouteImport } from './routes/_authenticated/fulfillment.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngineerRoute = AuthenticatedEngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionsRoute =
  AuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChiefRoute = AuthenticatedChiefRouteImport.update({
  id: '/chief',
  path: '/chief',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFulfillmentIdRoute =
  AuthenticatedFulfillmentIdRouteImport.update({
    id: '/fulfillment/$id',
    path: '/fulfillment/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chief': typeof AuthenticatedChiefRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/engineer': typeof AuthenticatedEngineerRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/fulfillment/$id': typeof AuthenticatedFulfillmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chief': typeof AuthenticatedChiefRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/engineer': typeof AuthenticatedEngineerRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/fulfillment/$id': typeof AuthenticatedFulfillmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chief': typeof AuthenticatedChiefRoute
  '/_authenticated/commissions': typeof AuthenticatedCommissionsRoute
  '/_authenticated/engineer': typeof AuthenticatedEngineerRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/fulfillment/$id': typeof AuthenticatedFulfillmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/chief'
    | '/commissions'
    | '/engineer'
    | '/sales'
    | '/fulfillment/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/chief'
    | '/commissions'
    | '/engineer'
    | '/sales'
    | '/fulfillment/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/chief'
    | '/_authenticated/commissions'
    | '/_authenticated/engineer'
    | '/_authenticated/sales'
    | '/_authenticated/fulfillment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineer': {
      id: '/_authenticated/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof AuthenticatedEngineerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissions': {
      id: '/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chief': {
      id: '/_authenticated/chief'
      path: '/chief'
      fullPath: '/chief'
      preLoaderRoute: typeof AuthenticatedChiefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fulfillment/$id': {
      id: '/_authenticated/fulfillment/$id'
      path: '/fulfillment/$id'
      fullPath: '/fulfillment/$id'
      preLoaderRoute: typeof AuthenticatedFulfillmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChiefRoute: typeof AuthenticatedChiefRoute
  AuthenticatedCommissionsRoute: typeof AuthenticatedCommissionsRoute
  AuthenticatedEngineerRoute: typeof AuthenticatedEngineerRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedFulfillmentIdRoute: typeof AuthenticatedFulfillmentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChiefRoute: AuthenticatedChiefRoute,
  AuthenticatedCommissionsRoute: AuthenticatedCommissionsRoute,
  AuthenticatedEngineerRoute: AuthenticatedEngineerRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedFulfillmentIdRoute: AuthenticatedFulfillmentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
