/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedEngineerRouteImport } from './routes/_authenticated/engineer'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCommissionsRouteImport } from './routes/_authenticated/commissions'
import { Route as AuthenticatedChiefRouteImport } from './routes/_authenticated/chief'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedUserIdRouteImport } from './routes/_authenticated/user.$id'
import { Route as AuthenticatedFulfillmentIdRouteImport } from './routes/_authenticated/fulfillment.$id'
import { Route as AuthenticatedCrmVisitsRouteImport } from './routes/_authenticated/crm.visits'
import { Route as AuthenticatedCrmSettingsRouteImport } from './routes/_authenticated/crm.settings'
import { Route as AuthenticatedCrmServicesRouteImport } from './routes/_authenticated/crm.services'
import { Route as AuthenticatedCrmSchoolsRouteImport } from './routes/_authenticated/crm.schools'
import { Route as AuthenticatedCrmSalesRouteImport } from './routes/_authenticated/crm.sales'
import { Route as AuthenticatedCrmProjectsRouteImport } from './routes/_authenticated/crm.projects'
import { Route as AuthenticatedCrmMachinesRouteImport } from './routes/_authenticated/crm.machines'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm.leads'
import { Route as AuthenticatedCrmInventoryRouteImport } from './routes/_authenticated/crm.inventory'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEngineerRoute = AuthenticatedEngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionsRoute =
  AuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChiefRoute = AuthenticatedChiefRouteImport.update({
  id: '/chief',
  path: '/chief',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedUserIdRoute = AuthenticatedUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFulfillmentIdRoute =
  AuthenticatedFulfillmentIdRouteImport.update({
    id: '/fulfillment/$id',
    path: '/fulfillment/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmVisitsRoute = AuthenticatedCrmVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmSettingsRoute =
  AuthenticatedCrmSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmServicesRoute =
  AuthenticatedCrmServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmSchoolsRoute = AuthenticatedCrmSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmSalesRoute = AuthenticatedCrmSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmProjectsRoute =
  AuthenticatedCrmProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmMachinesRoute =
  AuthenticatedCrmMachinesRouteImport.update({
    id: '/machines',
    path: '/machines',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmInventoryRoute =
  AuthenticatedCrmInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chief': typeof AuthenticatedChiefRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/engineer': typeof AuthenticatedEngineerRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/crm/inventory': typeof AuthenticatedCrmInventoryRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/machines': typeof AuthenticatedCrmMachinesRoute
  '/crm/projects': typeof AuthenticatedCrmProjectsRoute
  '/crm/sales': typeof AuthenticatedCrmSalesRoute
  '/crm/schools': typeof AuthenticatedCrmSchoolsRoute
  '/crm/services': typeof AuthenticatedCrmServicesRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/visits': typeof AuthenticatedCrmVisitsRoute
  '/fulfillment/$id': typeof AuthenticatedFulfillmentIdRoute
  '/user/$id': typeof AuthenticatedUserIdRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chief': typeof AuthenticatedChiefRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/engineer': typeof AuthenticatedEngineerRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/crm/inventory': typeof AuthenticatedCrmInventoryRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/machines': typeof AuthenticatedCrmMachinesRoute
  '/crm/projects': typeof AuthenticatedCrmProjectsRoute
  '/crm/sales': typeof AuthenticatedCrmSalesRoute
  '/crm/schools': typeof AuthenticatedCrmSchoolsRoute
  '/crm/services': typeof AuthenticatedCrmServicesRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/visits': typeof AuthenticatedCrmVisitsRoute
  '/fulfillment/$id': typeof AuthenticatedFulfillmentIdRoute
  '/user/$id': typeof AuthenticatedUserIdRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chief': typeof AuthenticatedChiefRoute
  '/_authenticated/commissions': typeof AuthenticatedCommissionsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/engineer': typeof AuthenticatedEngineerRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/crm/inventory': typeof AuthenticatedCrmInventoryRoute
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/_authenticated/crm/machines': typeof AuthenticatedCrmMachinesRoute
  '/_authenticated/crm/projects': typeof AuthenticatedCrmProjectsRoute
  '/_authenticated/crm/sales': typeof AuthenticatedCrmSalesRoute
  '/_authenticated/crm/schools': typeof AuthenticatedCrmSchoolsRoute
  '/_authenticated/crm/services': typeof AuthenticatedCrmServicesRoute
  '/_authenticated/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/_authenticated/crm/visits': typeof AuthenticatedCrmVisitsRoute
  '/_authenticated/fulfillment/$id': typeof AuthenticatedFulfillmentIdRoute
  '/_authenticated/user/$id': typeof AuthenticatedUserIdRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/chief'
    | '/commissions'
    | '/crm'
    | '/engineer'
    | '/sales'
    | '/crm/inventory'
    | '/crm/leads'
    | '/crm/machines'
    | '/crm/projects'
    | '/crm/sales'
    | '/crm/schools'
    | '/crm/services'
    | '/crm/settings'
    | '/crm/visits'
    | '/fulfillment/$id'
    | '/user/$id'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/chief'
    | '/commissions'
    | '/engineer'
    | '/sales'
    | '/crm/inventory'
    | '/crm/leads'
    | '/crm/machines'
    | '/crm/projects'
    | '/crm/sales'
    | '/crm/schools'
    | '/crm/services'
    | '/crm/settings'
    | '/crm/visits'
    | '/fulfillment/$id'
    | '/user/$id'
    | '/crm'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/chief'
    | '/_authenticated/commissions'
    | '/_authenticated/crm'
    | '/_authenticated/engineer'
    | '/_authenticated/sales'
    | '/_authenticated/crm/inventory'
    | '/_authenticated/crm/leads'
    | '/_authenticated/crm/machines'
    | '/_authenticated/crm/projects'
    | '/_authenticated/crm/sales'
    | '/_authenticated/crm/schools'
    | '/_authenticated/crm/services'
    | '/_authenticated/crm/settings'
    | '/_authenticated/crm/visits'
    | '/_authenticated/fulfillment/$id'
    | '/_authenticated/user/$id'
    | '/_authenticated/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engineer': {
      id: '/_authenticated/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof AuthenticatedEngineerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissions': {
      id: '/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chief': {
      id: '/_authenticated/chief'
      path: '/chief'
      fullPath: '/chief'
      preLoaderRoute: typeof AuthenticatedChiefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/user/$id': {
      id: '/_authenticated/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof AuthenticatedUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fulfillment/$id': {
      id: '/_authenticated/fulfillment/$id'
      path: '/fulfillment/$id'
      fullPath: '/fulfillment/$id'
      preLoaderRoute: typeof AuthenticatedFulfillmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/visits': {
      id: '/_authenticated/crm/visits'
      path: '/visits'
      fullPath: '/crm/visits'
      preLoaderRoute: typeof AuthenticatedCrmVisitsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/settings': {
      id: '/_authenticated/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof AuthenticatedCrmSettingsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/services': {
      id: '/_authenticated/crm/services'
      path: '/services'
      fullPath: '/crm/services'
      preLoaderRoute: typeof AuthenticatedCrmServicesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/schools': {
      id: '/_authenticated/crm/schools'
      path: '/schools'
      fullPath: '/crm/schools'
      preLoaderRoute: typeof AuthenticatedCrmSchoolsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/sales': {
      id: '/_authenticated/crm/sales'
      path: '/sales'
      fullPath: '/crm/sales'
      preLoaderRoute: typeof AuthenticatedCrmSalesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/projects': {
      id: '/_authenticated/crm/projects'
      path: '/projects'
      fullPath: '/crm/projects'
      preLoaderRoute: typeof AuthenticatedCrmProjectsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/machines': {
      id: '/_authenticated/crm/machines'
      path: '/machines'
      fullPath: '/crm/machines'
      preLoaderRoute: typeof AuthenticatedCrmMachinesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/inventory': {
      id: '/_authenticated/crm/inventory'
      path: '/inventory'
      fullPath: '/crm/inventory'
      preLoaderRoute: typeof AuthenticatedCrmInventoryRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
  }
}

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmInventoryRoute: typeof AuthenticatedCrmInventoryRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedCrmMachinesRoute: typeof AuthenticatedCrmMachinesRoute
  AuthenticatedCrmProjectsRoute: typeof AuthenticatedCrmProjectsRoute
  AuthenticatedCrmSalesRoute: typeof AuthenticatedCrmSalesRoute
  AuthenticatedCrmSchoolsRoute: typeof AuthenticatedCrmSchoolsRoute
  AuthenticatedCrmServicesRoute: typeof AuthenticatedCrmServicesRoute
  AuthenticatedCrmSettingsRoute: typeof AuthenticatedCrmSettingsRoute
  AuthenticatedCrmVisitsRoute: typeof AuthenticatedCrmVisitsRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmInventoryRoute: AuthenticatedCrmInventoryRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedCrmMachinesRoute: AuthenticatedCrmMachinesRoute,
  AuthenticatedCrmProjectsRoute: AuthenticatedCrmProjectsRoute,
  AuthenticatedCrmSalesRoute: AuthenticatedCrmSalesRoute,
  AuthenticatedCrmSchoolsRoute: AuthenticatedCrmSchoolsRoute,
  AuthenticatedCrmServicesRoute: AuthenticatedCrmServicesRoute,
  AuthenticatedCrmSettingsRoute: AuthenticatedCrmSettingsRoute,
  AuthenticatedCrmVisitsRoute: AuthenticatedCrmVisitsRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChiefRoute: typeof AuthenticatedChiefRoute
  AuthenticatedCommissionsRoute: typeof AuthenticatedCommissionsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedEngineerRoute: typeof AuthenticatedEngineerRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedFulfillmentIdRoute: typeof AuthenticatedFulfillmentIdRoute
  AuthenticatedUserIdRoute: typeof AuthenticatedUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChiefRoute: AuthenticatedChiefRoute,
  AuthenticatedCommissionsRoute: AuthenticatedCommissionsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedEngineerRoute: AuthenticatedEngineerRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedFulfillmentIdRoute: AuthenticatedFulfillmentIdRoute,
  AuthenticatedUserIdRoute: AuthenticatedUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
